// movies load:
export const LOADING_MOVIES = 'LOADING_MOVIES'
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED'

// movies search:
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
