// get movies:
export const LOADING_MOVIES = 'LOADING_MOVIES'
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED'

// movies search:
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

// get genres:
export const LOADING_GENRES = 'LOADING_GENRES'
export const LOAD_GENRES_SUCCESS = 'LOAD_GENRES_SUCCESS'
export const LOAD_GENRES_FAILED = 'LOAD_GENRES_FAILED'

// genre filters:
export const SELECT_GENRE = 'SELECT_GENRE'


// get movies by genre:
export const LOADING_MOVIE_BY_GENRES = 'LOADING_MOVIE_BY_GENRES'
export const LOAD_MOVIE_BY_GENRES_SUCCESS = 'LOAD_MOVIE_BY_GENRES_SUCCESS'
export const LOAD_MOVIE_BY_GENRES_FAILED = 'LOAD_MOVIE_BY_GENRES_FAILED'

// get movies by genre:
export const LOADING_MOVIE_BY_TITLE = 'LOADING_MOVIE_BY_TITLE'
export const LOAD_MOVIE_BY_TITLE_SUCCESS = 'LOAD_MOVIE_BY_TITLE_SUCCESS'
export const LOAD_MOVIE_BY_TITLE_FAILED = 'LOAD_MOVIE_BY_TITLE_FAILED'
